# LCM channels to read data from
is_simulation: false
channel_x: "TRIFINGER_STATE"
channel_u: "TRIFINGER_INPUT"
channel_x_sim: "TRIFINGER_STATE_SIMULATION"
channel_u_sim: "TRIFINGER_INPUT_SIMULATION"
channel_osc: "OSC_DEBUG_TRIFINGER"
channel_fingertip_delta_pos: "FINGERTIPS_DELTA_POSITION"
channel_cube: "CUBE_STATE"
plot_style: 'compact' # compact, paper, default

start_time: 0
duration: -1

# Desired RobotOutput plots
plot_joint_positions: false
plot_joint_velocities: false
plot_measured_efforts: false
plot_commanded_efforts: false

special_positions_to_plot: []
special_velocities_to_plot: []
special_efforts_to_plot: []

# Finite State Machine Names
fsm_state_names: [ 'Left Stance (LS)', 'Right Stance (RS)', 'Left Flight (LF)', 'Right Flight (RF)' ]

# Desired osc plots
plot_qp_costs: false
plot_qp_solve_time: false
plot_qp_solutions: false
plot_tracking_costs: false
plot_active_tracking_datas: false
tracking_datas_to_plot:
  fingertip_0_target: {'dims': [0, 1, 2], 'derivs': ['pos']}
#  fingertip_120_target: {'dims': [2], 'derivs': ['pos', 'vel']}
#  fingertip_240_target: {'dims': [2], 'derivs': ['pos', 'vel']}
plot_object_state: false